import json
from pathlib import Path

import pandas as pd

RESULTS = Path("results")
RUN = RESULTS / "run7_2018_2021"


def main() -> None:
    base = json.loads((RESULTS / "baseline.json").read_text())
    run = json.loads((RUN / "metrics.json").read_text())["test"]
    rows = []
    for task, name in [("anomaly", "Anomaly"), ("primary_problem", "Primary Problem")]:
        for metric in ("macro_f1", "micro_f1", "hamming_loss"):
            rows.append({"task": name, "metric": metric, "tfidf_svm": base[task][metric], "deberta_lora": run[task][metric]})
    overall = pd.DataFrame(rows)

    summary = pd.read_csv(RESULTS / "trends" / "label_trend_summary.csv")
    trends = summary[summary["mean_share"] > 0.05][
        ["label", "mean_share", "tracking_corr", "true_change", "pred_change", "true_change_points", "pred_change_points"]
    ]

    topics = pd.read_csv(RESULTS / "topics" / "topics.csv")
    topics = topics[topics["Topic"] != -1][["Topic", "Count", "top_words"]]

    parts = [
        "# Thesis tables (generated by scripts/make_tables.py)\n",
        "## Table 1. Test-set performance (2018-2021, chronological split, 3,027 test reports)\n",
        overall.round(3).to_markdown(index=False),
        "\n## Table 2. Label trends: tracking and change (labels above 5% mean share)\n",
        "tracking_corr: correlation of predicted vs true monthly share. *_change: last 12 months minus first 12 months.\n",
        trends.round(3).to_markdown(index=False),
        "\n## Table 3. BERTopic topics\n",
        topics.to_markdown(index=False),
    ]
    (RESULTS / "tables.md").write_text("\n".join(parts) + "\n")
    print(overall.round(3).to_string(index=False))


if __name__ == "__main__":
    main()
